version: "3.9"

services:
  gonnectbot:
    container_name: gonnectbot
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MUMBLE_SERVER=${MUMBLE_SERVER}
      - MUMBLE_USERNAME=${MUMBLE_USERNAME}
      - MUMBLE_PASSWORD=${MUMBLE_PASSWORD}
      - MUMBLE_INSECURE=${MUMBLE_INSECURE}
      - MUMBLE_CERT_FILE=certs/mumble-cert.pem
      - MUMBLE_KEY_FILE=certs/mumble-key.pem
      - MUMBLE_DEFAULT_STRING=${MUMBLE_DEFAULT_STRING}
      - MUMBLE_CHANNELS=${MUMBLE_CHANNELS}
    volumes:
      - ./certs:/etc/ssl/certs
    ports: 
      - 64738:64738
      - 64738:64738/udp